server:
  port: 8082
  tomcat:
    threads:
      max: 25
    accept-count: 25 #允许排队等待的线程
    max-connections: 100
feign:
  okhttp:
    enabled: true # 使用okhttp的连接池
  sentinel:
    enabled: true
# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123
hm:
  db:
    database: hm-cart
  swagger:
    title: "黑马商城购物车服务接口文档"
    desc: "黑马商城购物车服务接口文档"
    package: com.hmall.cart.controller

spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090
      http-method-specify: true # 开启请求方式前缀（请求方式+请求路径 作为簇点资源名称 ）